from database_setup import db, Recipe, Description

description_1 = Description(description='Whisk together soy sauce, sesame oil, olive oil, vinegar, peanut butter, cayenne pepper, ginger, garlic, and serrano in a small bowl; set aside. Toast spelt kernels in a dry skillet on medium-high heat until the kernels are browned and some have popped. Remove, place in a mesh strainer, and rinse well with cold water. Drain. Bring 6 cups of water to a boil in a large saucepan; add 1/2 teaspoon kosher salt and stir in spelt kernels. Return to a boil then cover, reduce heat to low, and simmer until tender, about 1 hour. Drain well and set aside to cool. While the spelt is simmering, fill a skillet with 1 quart water, 1/2 teaspoon salt, and onion. Bring to a boil over high heat. Add chicken breasts, reduce the heat to medium-low, cover, and simmer until the chicken is cooked through, about 15 minutes. Remove chicken from liquid and allow to cool. Once chicken is cool enough to handle, shred into bite-sized chunks and place in a large bowl. Stir in spelt, bell pepper, green onions, parsley, cilantro, carrots, and cabbage. Pour sauce over salad and stir well to combine.', recipe_name='Spicy Chicken and Spelt Salad')

description_2 = Description(description='Preheat oven to 350 degrees F (175 degrees C). Combine the seasoning, salt, mustard powder, garlic powder and black pepper; set aside. Rinse the chicken thoroughly, and remove the giblets. Place chicken in a 9x13 inch baking dish. Sprinkle 1 1/2 teaspoons of the spice mixture inside the chicken. Rub the remaining mixture on the outside of the chicken. Squeeze the juice of the 2 lemons into a small bowl or cup, and mix with the olive oil. Drizzle this oil/juice mixture over the chicken. Bake in the preheated oven for 1 1/2 hours, or until juices run clear, basting several times with the remaining oil mixtur', recipe_name='Lemon Herb Chicken')

description_3 = Description(description='Mix peas, green beans, corn, onion, celery, salt, and pepper together in a bowl. Combine sugar, oil, and vinegar in a saucepan over medium heat; cook and stir until sugar is dissolved, about 5 minutes. Pour mixture over vegetable mixture and stir to coat; refrigerate until flavors blend, 8 hours to overnight.', recipe_name='Vegetable Salad')

description_4 = Description(description='Preheat the oven to 400 degrees F (200 degrees C). Place chicken, onion, and celery in a Dutch oven. Sprinkle salt over the top of the chicken. Roast chicken, uncovered, in the preheated oven until chicken is no longer pink inside, the skin is browned, and an instant-read thermometer inserted into the thickest part of a thigh reads 160 degrees F (70 degrees C), 45 minutes to 1 hour. Transfer chicken to a plate until cool enough to handle. Once cool, pick the meat from the bones; set aside chicken breast meat in a bowl for another purpose. Cover bowl of breast meat with plastic wrap and refrigerate. Discard chicken skin. Remove chicken fat from Dutch oven, leaving the brown flavor bits in the bottom of the Dutch oven. (See note for reserving drippings if desired.) Place the Dutch oven over medium-high heat. Return chicken bones and dark meat from drumsticks and thighs to the pot. Add garlic cloves, ketchup and cold water. Bring to a boil, and use a spoon to scrape up and dissolve the brown flavor bits from the bottom of the Dutch oven. Reduce heat to low and simmer for 3 hours, adding more water if needed to retain same level. As broth simmers, occasionally skim off and discard any foam that rises to the surface. Remove and discard bones, meat and vegetables. Strain broth through a fine mesh sieve to serve or use in recipes', recipe_name='Chicken Broth')

description_5 = Description(description='In a small bowl, mix the maple syrup, soy sauce, garlic, garlic salt, and pepper. Place salmon in a shallow glass baking dish, and coat with the maple syrup mixture. Cover the dish, and marinate salmon in the refrigerator 30 minutes, turning once. Preheat oven to 400 degrees F (200 degrees C). Place the baking dish in the preheated oven, and bake salmon uncovered 20 minutes, or until easily flaked with a fork', recipe_name='Maple Salmon')

description_6 = Description(description='In a large stockpot, saute the onions in oil until they are glossy. Stir in garlic, paprika, celery, carrots, and saute for 10 minutes. Once the vegetables have sauteed for 10 minutes stir in tomatoes, chicken stock, lentils, bay leaves, salt, and pepper. Stir well, then add the wine and bring the mixture to a boil. Slowly reduce the heat and cook for 1 hour on low to medium heat; or until the lentils are tender. Sprinkle the soup with parsley and Parmesan (optional) before serving.', recipe_name='Lentil Soup')

description_7 = Description(description='Add 2/3 cup salad dressing to the cubed chicken and stir together. Cook pasta per package directions. Drain and rinse. Add the pasta to the chicken and dressing and toss. Pour enough dressing on to coat everything (or to your taste) and add the chopped tomato. Toss to coat. Ready to serve!', recipe_name='Italian Chicken Pasta')

description_8 = Description(description='Preheat the oven to 400 degrees F (200 degrees C). In a large bowl, toss broccoli florets with the extra virgin olive oil, sea salt, pepper and garlic. ... Bake in the preheated oven until florets are tender enough to pierce the stems with a fork, 15 to 20 minutes.', recipe_name='Garlic Lemon Broccol')

description_9 = Description(description='If grilling, preheat an outdoor grill for high heat, and lightly oil a sheet of aluminum foil. If baking, preheat oven to 375 degrees F (190 degrees C), and lightly oil a baking sheet. In a medium bowl, mash black beans with a fork until thick and pasty. In a food processor, finely chop bell pepper, onion, and garlic. Then stir into mashed beans. In a small bowl, stir together egg, chili powder, cumin, and chili sauce. Stir the egg mixture into the mashed beans. Mix in bread crumbs until the mixture is sticky and holds together. Divide mixture into four patties. If grilling, place patties on foil, and grill about 8 minutes on each side. If baking, place patties on baking sheet, and bake about 10 minutes on each side.', recipe_name='Black Bean Veggie Burger')



db.session.add(description_1)
db.session.add(description_2)
db.session.add(description_3)

db.session.commit()
