from database_setup import db, Recipe, Ingredient


ingredient_4 = Ingredient(name='cabbage', recipe_name='Spicy Chicken and Spelt Salad')
ingredient_5 = Ingredient(name='sesame oil', recipe_name='Spicy Chicken and Spelt Salad')
ingredient_6 = Ingredient(name='onion', recipe_name='Spicy Chicken and Spelt Salad')
ingredient_7 = Ingredient(name='peanut butter', recipe_name='Spicy Chicken and Spelt Salad')
ingredient_8 = Ingredient(name='chicken', recipe_name='Spicy Chicken and Spelt Salad')
ingredient_9 = Ingredient(name='chicken', recipe_name='Lemon Herb Chicken')
ingredient_10 = Ingredient(name='lemon', recipe_name='Lemon Herb Chicken')
ingredient_11= Ingredient(name='oregano', recipe_name='Lemon Herb Chicken')
ingredient_12= Ingredient(name='cilantro', recipe_name='Vegetable Salad')
ingredient_13= Ingredient(name='lemon', recipe_name='Vegetable Salad')
ingredient_14= Ingredient(name='tomato', recipe_name='Vegetable Salad')
ingredient_15= Ingredient(name='onion', recipe_name='Vegetable Salad')
ingredient_16 = Ingredient(name='syrup', recipe_name='Maple Salmon')
ingredient_17= Ingredient(name='salmon', recipe_name='Maple Salmon')
ingredient_18 = Ingredient(name='chicken', recipe_name='Honey Mustard Chicken')
ingredient_19 = Ingredient(name='basil', recipe_name='Honey Mustard Chicken')
ingredient_20 = Ingredient(name='parsley', recipe_name='Honey Mustard Chicken')
ingredient_21 = Ingredient(name='honey', recipe_name='Honey Mustard Chicken')
ingredient_22 = Ingredient(name='black beans', recipe_name='Black Bean Veggie Burger')
ingredient_23 = Ingredient(name='bell pepper', recipe_name='Black Bean Veggie Burger')
ingredient_24 = Ingredient(name='onion', recipe_name='Black Bean Veggie Burger')
ingredient_25 = Ingredient(name='chili', recipe_name='Black Bean Veggie Burger')
ingredient_26 = Ingredient(name='bread', recipe_name='Black Bean Veggie Burger')
ingredient_27 = Ingredient(name='egg', recipe_name='Black Bean Veggie Burger')
ingredient_28 = Ingredient(name='tomato', recipe_name='Lentil Soup')
ingredient_29 = Ingredient(name='lentil', recipe_name='Lentil Soup')
ingredient_30 = Ingredient(name='onion', recipe_name='Lentil Soup')
ingredient_31 = Ingredient(name='olive oil', recipe_name='Lentil Soup')
ingredient_32 = Ingredient(name='basil', recipe_name='Lentil Soup')
ingredient_33 = Ingredient(name='noodles', recipe_name='Chicken Broth')
ingredient_34 = Ingredient(name='broth', recipe_name='Chicken Broth')
ingredient_35= Ingredient(name='onion', recipe_name='Chicken Broth')
ingredient_36= Ingredient(name='cornstarch', recipe_name='Chicken Broth')
ingredient_37= Ingredient(name='chicken', recipe_name='Chicken Broth')
ingredient_38= Ingredient(name='pasta', recipe_name='Italian Chicken Pasta')
ingredient_39= Ingredient(name='onion', recipe_name='Italian Chicken Pasta')
ingredient_40= Ingredient(name='cheese', recipe_name='Italian Chicken Pasta')
ingredient_41= Ingredient(name='parsley', recipe_name='Italian Chicken Pasta')
ingredient_42= Ingredient(name='lemon', recipe_name='Italian Chicken Pasta')
ingredient_43= Ingredient(name='chicken', recipe_name='Italian Chicken Pasta')
ingredient_44= Ingredient(name='tomato', recipe_name='Italian Chicken Pasta')
ingredient_45= Ingredient(name='basil', recipe_name='Baked Potatoes')
ingredient_46= Ingredient(name='parsley', recipe_name='Baked Potatoes')
ingredient_47= Ingredient(name='potato', recipe_name='Baked Potatoes')
ingredient_48= Ingredient(name='oregano', recipe_name='Baked Potatoes')
ingredient_49= Ingredient(name='broccoli', recipe_name='Garlic Lemon Broccoli')
ingredient_50= Ingredient(name='olive oil', recipe_name='Garlic Lemon Broccoli')
ingredient_51= Ingredient(name='garlic', recipe_name='Garlic Lemon Broccoli')
ingredient_52= Ingredient(name='lemon', recipe_name='Garlic Lemon Broccoli')
ingredient_53= Ingredient(name='onion', recipe_name='White Bean Chicken Chili')
ingredient_54= Ingredient(name='oregano', recipe_name='White Bean Chicken Chili')
ingredient_55= Ingredient(name='corn', recipe_name='White Bean Chicken Chili')
ingredient_56= Ingredient(name='chicken', recipe_name='White Bean Chicken Chili')
ingredient_57= Ingredient(name='white bean', recipe_name='White Bean Chicken Chili')
ingredient_58= Ingredient(name='garlic', recipe_name='White Bean Chicken Chili')
ingredient_59= Ingredient(name='green chili', recipe_name='White Bean Chicken Chili')
ingredient_60= Ingredient(name='garlic', recipe_name='Potato Salad')
ingredient_61= Ingredient(name='mustard', recipe_name='Potato Salad')
ingredient_62= Ingredient(name='mayonnaise', recipe_name='Potato Salad')
ingredient_63= Ingredient(name='potato', recipe_name='Potato Salad')
ingredient_64= Ingredient(name='pickle', recipe_name='Potato Salad')
ingredient_65= Ingredient(name='egg', recipe_name='Potato Salad')
ingredient_66= Ingredient(name='pasta', recipe_name='Penne Pasta with Spinach and Bacon')
ingredient_67= Ingredient(name='olive oil', recipe_name='Penne Pasta with Spinach and Bacon')
ingredient_68= Ingredient(name='bacon', recipe_name='Penne Pasta with Spinach and Bacon')
ingredient_69= Ingredient(name='garlic', recipe_name='Penne Pasta with Spinach and Bacon')
ingredient_70= Ingredient(name='tomato', recipe_name='Penne Pasta with Spinach and Bacon')
ingredient_71= Ingredient(name='spinach', recipe_name='Penne Pasta with Spinach and Bacon')


db.session.add(ingredient_4)
db.session.add(ingredient_5)
db.session.add(ingredient_6)
db.session.add(ingredient_7)
db.session.add(ingredient_8)
db.session.add(ingredient_9)
db.session.add(ingredient_10)
db.session.add(ingredient_11)
db.session.add(ingredient_12)
db.session.add(ingredient_13)
db.session.add(ingredient_14)
db.session.add(ingredient_15)
db.session.add(ingredient_16)
db.session.add(ingredient_17)
db.session.add(ingredient_18)
db.session.add(ingredient_19)
db.session.add(ingredient_20)

db.session.add(ingredient_21)
db.session.add(ingredient_22)
db.session.add(ingredient_23)
db.session.add(ingredient_24)
db.session.add(ingredient_25)
db.session.add(ingredient_26)
db.session.add(ingredient_27)
db.session.add(ingredient_28)
db.session.add(ingredient_29)
db.session.add(ingredient_30)

db.session.add(ingredient_31)
db.session.add(ingredient_32)
db.session.add(ingredient_33)
db.session.add(ingredient_34)
db.session.add(ingredient_35)
db.session.add(ingredient_36)
db.session.add(ingredient_37)
db.session.add(ingredient_38)
db.session.add(ingredient_39)
db.session.add(ingredient_40)

db.session.add(ingredient_41)
db.session.add(ingredient_42)
db.session.add(ingredient_43)
db.session.add(ingredient_44)
db.session.add(ingredient_45)
db.session.add(ingredient_46)
db.session.add(ingredient_47)
db.session.add(ingredient_48)
db.session.add(ingredient_49)
db.session.add(ingredient_50)

db.session.add(ingredient_51)
db.session.add(ingredient_52)
db.session.add(ingredient_53)
db.session.add(ingredient_54)
db.session.add(ingredient_55)
db.session.add(ingredient_56)
db.session.add(ingredient_57)
db.session.add(ingredient_58)
db.session.add(ingredient_59)
db.session.add(ingredient_60)

db.session.add(ingredient_61)
db.session.add(ingredient_62)
db.session.add(ingredient_63)
db.session.add(ingredient_64)
db.session.add(ingredient_65)
db.session.add(ingredient_66)
db.session.add(ingredient_67)
db.session.add(ingredient_68)
db.session.add(ingredient_69)
db.session.add(ingredient_70)

db.session.add(ingredient_71)


db.session.commit()
