from database_setup import db, Recipe, Ingredient

recipe_1 = Recipe(name='Mapo')
recipe_2 = Recipe(name='Hongshao')
recipe_3 = Recipe(name='Jiaozi')
recipe_4 = Recipe(name='Spicy Chiken and Spelt Salad')
recipe_5 = Recipe(name='Lemon Herb Chicken')
recipe_6 = Recipe(name='Vegetable Salad')
recipe_7 = Recipe(name='Maple Salmon')
recipe_8 = Recipe(name='Honey Mustard Chicken')
recipe_9 = Recipe(name='Black Bean Veggie Burger')
recipe_10 = Recipe(name='Lentil Soup')
recipe_11 = Recipe(name='Chicken Broth')
recipe_12 = Recipe(name='Italian Chicken Pasta')
recipe_13 = Recipe(name='Baked Potatoes')
recipe_14 = Recipe(name='Garlic Lemon Broccoli')
recipe_15 = Recipe(name='White Bean Chicken Chili')
recipe_16 = Recipe(name='Potato Salad')
recipe_17 = Recipe(name='Penne Pasta with Spinach and Bacon')


db.session.add(recipe_1)
db.session.add(recipe_2)
db.session.add(recipe_3)
db.session.add(recipe_4)
db.session.add(recipe_5)
db.session.add(recipe_6)
db.session.add(recipe_7)
db.session.add(recipe_8)
db.session.add(recipe_9)
db.session.add(recipe_10)
db.session.add(recipe_11)
db.session.add(recipe_12)
db.session.add(recipe_13)
db.session.add(recipe_14)
db.session.add(recipe_15)
db.session.add(recipe_16)
db.session.add(recipe_17)

db.session.commit()
